CORPUS = [
    "Le cerveau humain contient environ 86 milliards de neurones.",
    "Les neurones communiquent entre eux grâce aux synapses et aux neurotransmetteurs.",
    "La plasticité cérébrale permet au cerveau de s'adapter aux expériences et à l'apprentissage.",
    "Les neurotransmetteurs comme la dopamine influencent l'humeur, la motivation et la mémoire.",
    "L'hippocampe joue un rôle clé dans la formation des souvenirs et la mémoire du cerveau.",
    "Les neurones moteurs transmettent les signaux du cerveau aux muscles et aux organes.",
    "La mémoire à court terme dépend fortement du cortex préfrontal et de l'activité neuronale.",
    "Les synapses excitatrices et inhibitrices régulent l'activité des neurones et la communication cérébrale.",
    "La dopamine est essentielle pour le système de récompense du cerveau et pour l'apprentissage.",
    "Les circuits neuronaux peuvent se réorganiser après une lésion cérébrale ou des traumatismes.",
    "Le cortex visuel et le cortex préfrontal sont responsables du traitement des informations visuelles et cognitives.",
    "Les axones permettent de transmettre les signaux électriques sur de longues distances entre neurones.",
    "La plasticité synaptique est la base de l'apprentissage, de la mémoire et de la communication neuronale.",
    "Les neurones sensoriels détectent les stimuli environnementaux et transmettent l'information au cerveau.",
    "Le cerveau droit et le cerveau gauche ont des fonctions complémentaires dans le traitement des informations.",
    "La sérotonine et la dopamine régulent l'humeur, le sommeil, l'appétit et la motivation.",
    "Les dendrites reçoivent les signaux des autres neurones et participent à la plasticité cérébrale.",
    "Les maladies neurodégénératives affectent la structure et la fonction des neurones et des synapses.",
    "L'amygdale est impliquée dans les émotions, la peur et le traitement des souvenirs.",
    "L'axone et la dendrite sont des structures essentielles pour la communication neuronale et la transmission des signaux.",
]
